(function() {
  var canvas_size = 750;
  var canvas_dimension = 50;
  var start_point = canvas_dimension / 2;
  var initial_states = [
    [
      {x: start_point, y: start_point},
      {x: start_point + 1, y: start_point},
      {x: start_point + 1, y: start_point + 2},
      {x: start_point + 3, y: start_point + 1},
      {x: start_point + 4, y: start_point},
      {x: start_point + 5, y: start_point},
      {x: start_point + 6, y: start_point},
    ],
    [
      {x: start_point + 1, y: start_point},
      {x: start_point + 2, y: start_point},
      {x: start_point + 3, y: start_point},
      {x: start_point + 4, y: start_point},
      {x: start_point + 5, y: start_point},
      {x: start_point + 6, y: start_point},
      {x: start_point + 7, y: start_point},
      {x: start_point + 8, y: start_point},
      {x: start_point + 9, y: start_point},
      {x: start_point + 10, y: start_point},
      {x: start_point + 11, y: start_point},
      {x: start_point + 13, y: start_point},
      {x: start_point + 14, y: start_point},
      {x: start_point + 15, y: start_point},
      {x: start_point + 16, y: start_point},
      {x: start_point + 17, y: start_point},
      {x: start_point + 18, y: start_point},
      {x: start_point + 19, y: start_point},
      {x: start_point + 20, y: start_point},
      {x: start_point - 1, y: start_point},
      {x: start_point - 2, y: start_point},
      {x: start_point - 3, y: start_point},
      {x: start_point - 4, y: start_point},
      {x: start_point - 5, y: start_point},
      {x: start_point - 6, y: start_point},
      {x: start_point - 7, y: start_point},
      {x: start_point - 8, y: start_point},
      {x: start_point - 9, y: start_point},
      {x: start_point - 10, y: start_point},
      {x: start_point - 11, y: start_point},
      {x: start_point - 13, y: start_point},
      {x: start_point - 14, y: start_point},
      {x: start_point - 15, y: start_point},
      {x: start_point - 16, y: start_point},
      {x: start_point - 17, y: start_point},
      {x: start_point - 18, y: start_point},
      {x: start_point - 19, y: start_point},
      {x: start_point - 20, y: start_point},
    ],
    [
      {x: start_point, y: start_point},
      {x: start_point + 1, y: start_point + 1},
      {x: start_point + 2, y: start_point + 3},
      {x: start_point + 1, y: start_point + 2},
      {x: start_point + 1, y: start_point + 3},
      {x: start_point + 4, y: start_point + 3},
      {x: start_point + 2, y: start_point + 2},
    ],
    [
      {x: start_point - 1, y: start_point - 1},
      {x: start_point - 2, y: start_point - 1},
      {x: start_point, y: start_point - 1},
      {x: start_point - 1, y: start_point - 2},
      {x: start_point - 10, y: start_point - 10},
      {x: start_point - 11, y: start_point - 10},
      {x: start_point - 9, y: start_point - 10},
      {x: start_point - 10, y: start_point - 11},
      {x: start_point + 7, y: start_point - 10},
      {x: start_point + 8, y: start_point - 10},
      {x: start_point + 6, y: start_point - 10},
      {x: start_point + 7, y: start_point - 11},
      {x: start_point + 7, y: start_point + 8},
      {x: start_point + 8, y: start_point + 8},
      {x: start_point + 6, y: start_point + 8},
      {x: start_point + 7, y: start_point + 9},
      {x: start_point - 10, y: start_point + 8},
      {x: start_point - 11, y: start_point + 8},
      {x: start_point - 9, y: start_point + 8},
      {x: start_point - 10, y: start_point + 9},
    ],
  ];
  LIFE.initial_states = initial_states;
  LIFE.canvas_size = canvas_size;
  LIFE.canvas_dimension = canvas_dimension; 
})();
